### ISSUE TITLE
안녕하세요. kochat, kocrawl에 관한 질문입니다.

### ISSUE THREAD

**Issue by dnjzmaos147** [gusdnd852/kocrawl#2]
한국어 챗봇 오픈소스를 찾아보다가 kochat을 보고 개발을 해보고싶은데..
demo 버전을 실행해보니까 날씨,미세먼지,여행지 관련 close domain 이더라구요.
저는 법률관련 노무상담 챗봇을 만들고 싶은데 kocrawl은 네이버에서 검색결과를 크롤링해오는 방식 같은데
법률관련 같은 새로운 분야의 api를 추가하려면 어떻게 해야할까요?
답변해주시면 정말 감사하겠습니다.

아 그리고 혹시 날씨, 먼지, 관광지, OOD 같은 데이터셋들은 직접 구현 하신건가요?

**Comment by hyunwoongko** [comment]
안녕하세요. 데이터는 제가 다 만든게 맞구요. 새로운 분야의 API를 추가하신다는게, 이미 API를 보유하고 계신건지 아니면 크롤링을 해야하는 상황인지 알 수 있을까요?

**Comment by dnjzmaos147** [comment]
답변감사합니다.
데이터는 아직 구현중입니다. 
혹시 웹 프레임워크로 spring을 사용하려고 하는데  kochat을 서버로만 구현하고 데이터를 api로 호출하고싶은데 가능할까요?

**Comment by hyunwoongko** [comment]
네 가능합니다. 코챗을 view없이 restful 서버로만 활용할 수 있습니다. 
자세한 사항은 문서를 참고해보세요.
https://github.com/sinabro-team/kochat/blob/master/docs/04_usage.md#45-from-kochatapp

이용 중에 사용하기 어렵거나 이해가 안가시는 부분 있으면 바로 이슈 남겨주세요!

**Comment by dnjzmaos147** [comment]
답변 감사합니다!
법률관련 데이터를 공공데이터 생활법률 https://data.go.kr/data/15028606/openapi.do 에서 쓰고싶은데
kocrawl 라이브러리에 새로운분야를 추가하려면 직접 라이브러리를 수정해야만 할까요??

**Comment by hyunwoongko** [comment]
말씀하신 데이터에 대해 잘 몰라서... 음.. 어떤 형식의 데이터인지 간단하게만 알려주실 수 있으실까요?
(데이터를 보려고 했는데, 활용 신청을 해야 받아볼 수 있네요)

**Comment by dnjzmaos147** [comment]
`<item>
<middleCategory>
    <![CDATA[ 주택임대차 ]]>
</middleCategory>
<articleNo>
    <![CDATA[ 111344001 ]]>
</articleNo>
<answer>
    <![CDATA[ 임대인은 임차인이 보증금을 수령 거절할 경우 임차권등기말소를 하기 위해서는, 법원에 보증금과 이자(임차인이 이사를 가 
   면서 임대인에게 주택을 인도한 다음 날 부터 공탁한 일자까지의 이자)를 합산한 금액을 변제공탁 한 후, 임대인이 임차권등기 취소신청을 
    하여 법원의 결정을 받아 임차권등기의 집행해제를 신청하여야 말소가 될 것으로 보입니다. ]]>
</answer>
<mainCategory>
    <![CDATA[ 부동산임대차 ]]>
</mainCategory>
<question>
    <![CDATA[ 임차인이 수 개월 째 월세를 주지 않아 월세를 독촉하였음에도 여전히 미지급 상태입니다. 집을 빼달라고 했더니 임차인은 이 
   사를 가면서 임차권등기명령을 걸어 놓았습니다. 임차권등기명령을 말소하기 위해 임차인에게 보증금을 지급하겠다고 계좌번호를 알려달 
   라고 하였으나, 답변을 피하고 연락도 없습니다. 임차권등기명령을 취소할 수 있는 방법이 없는지요. ]]>
</question>
<smallCategory>
    <![CDATA[ 보증금 ]]>
</smallCategory>
</item>
`

이런식으로 질문, 답변 xml형태 api 입니다.


혹시 Scenario 부분에 api 인자 부분에 들어가는 함수가 어떤 구조나 형식이 필요하나요?
`dust = Scenario(
    intent='dust',
    api=DustCrawler().request_debug,       #여기에는 어떤함수가 들어가야하나요??
    scenario={
        'LOCATION': [],
        'DATE': ['오늘']
    }
)`
kochat을 쓰고싶은데 제가 잘 몰라서 어렵네요.. 바쁘실텐데 자꾸 물어봐서 죄송합니다.
