### ISSUE TITLE
식당

### ISSUE THREAD

**Issue by hyeon312** [gusdnd852/kocrawl#3]
from kocrawl.restaurant import RestaurantCrawler

이 부분이 계속 로드가 안되길래 봤더니 

help(kocrawl)

Help on package kocrawl:

NAME
    kocrawl

PACKAGE CONTENTS
    answerer (package)
    base
    config
    daum_dict
    daum_news
    decorators
    dust
    editor (package)
    map
    retaurant  ---> **여기에 오타가 있었더라구요. s가 빠졌습니다.** 
    searcher (package)
    spell
    weather

소소하지만 피드 남깁니다 ^^

**Comment by hyunwoongko** [comment]
감사합니다~
